@extends('layout.app', ['showLayout' => false, 'isPrint' => true, 'title' => 'Financial Ledger Statement'])

@section('content')
    <!-- INTERNAL HEADER (Standalone) -->
    <div class="mb-10">
        <div class="flex justify-between items-start mb-6">
            <div class="space-y-1">
                <h1 class="text-huge">{{ get_setting('APP_NAME', 'Mini Lara') }}</h1>
                <p class="text-[12px] font-black text-tp uppercase tracking-tighter">{{ get_setting('APP_TAGLINE', 'Clean & Scalable System') }}</p>
            </div>
            <div class="text-right">
                <div class="px-6 py-2 bg-black text-white inline-block font-black text-xs uppercase rounded-lg mb-4">Ledger Statement</div>
                <div class="text-[10px] font-black uppercase tracking-tighter">
                    Generated: {{ date('d M, Y h:i A') }}<br>
                    Account ID: #0002
                </div>
            </div>
        </div>
        <div class="text-[11px] font-bold uppercase leading-tight mb-6">
            {{ get_setting('APP_ADDRESS', 'Main City Road, Warehouse #12') }}<br>
            Contact: {{ get_setting('APP_PHONE1', '03330000000') }}
        </div>
        <div class="border-thick mb-10"></div>
    </div>

    <!-- High-Contrast Row -->
    <div class="grid grid-cols-2 gap-8 mb-12">
        <div class="box-outline flex flex-col justify-center">
            <h3 class="text-[9px] font-black uppercase mb-3 tracking-widest opacity-60">Statement For</h3>
            <div class="text-2xl font-black uppercase mb-1 tracking-tighter">Habib Manufacturing Co.</div>
            <div class="text-[11px] font-bold uppercase leading-relaxed">
                0333111222<br>
                Karachi, Pakistan
            </div>
        </div>
        <div class="box-black flex flex-col justify-center relative overflow-hidden">
            <h3 class="text-[9px] font-black uppercase mb-2 tracking-widest text-right opacity-70">Statement Closing Balance</h3>
            <div class="text-right">
                <div class="text-4xl font-black tracking-tighter">Rs. 50,000.00</div>
                <div class="text-[10px] font-black uppercase mt-1 opacity-80">Payable (Dues)</div>
            </div>
        </div>
    </div>

    <!-- Ledger Table -->
    <table class="w-full border-collapse mb-12">
        <thead>
            <tr class="table-header-gray">
                <th class="py-4 px-4 text-left border-black">Date</th>
                <th class="py-4 px-4 text-left border-black">Description</th>
                <th class="py-4 px-4 text-center border-black">Debit</th>
                <th class="py-4 px-4 text-center border-black">Credit</th>
                <th class="py-4 px-4 text-right border-black">Balance</th>
            </tr>
        </thead>
        <tbody class="divide-y divide-slate-200">
            <tr class="bg-slate-50/50">
                <td class="py-5 px-4 text-[10px] font-black uppercase">Brought Forward</td>
                <td class="py-5 px-4 text-[11px] font-black uppercase">Balance Brought Forward</td>
                <td class="py-5 px-4 text-center font-bold text-xs">-</td>
                <td class="py-5 px-4 text-center font-bold text-xs">-</td>
                <td class="py-5 px-4 text-right font-black text-xs">Rs. 50,000.00 <span class="text-[8px] opacity-60">DR</span></td>
            </tr>
        </tbody>
    </table>

    <!-- INTERNAL FOOTER (Signatures & Attribution) -->
    <div class="mt-auto pt-16">
        <div class="grid grid-cols-3 gap-10 px-10">
            <div class="text-center"><div class="w-full border-b border-black mb-2"></div><div class="text-[9px] font-black uppercase">Prepared By</div></div>
            <div class="text-center"><div class="w-full border-b border-black mb-2"></div><div class="text-[9px] font-black uppercase">Verified By</div></div>
            <div class="text-center"><div class="w-full border-b border-black mb-2"></div><div class="text-[9px] font-black uppercase">Customer Signature</div></div>
        </div>
        <div class="mt-16 pt-6 border-t border-black flex justify-between items-center font-semibold">
            <div class="text-[8px] uppercase tracking-tighter">Digitally Generated by {{ get_setting('APP_NAME') }}</div>
            <div class="text-[8px] uppercase tracking-widest text-right">
                Developed by <a href="{{ config('DEVELOPER_URL') }}" target="_blank" class="underline">{{ config('DEVELOPER_NAME') }}</a>
            </div>
        </div>
    </div>
@endsection
